### ISSUE TITLE
PHP 7.0 required for package due to use of coalesce function 

### ISSUE THREAD

**Issue by jodenis** [ntavelis/auth-email#12]
I did not see any requirements for PHP 7 in docs. Installed and got error when running 
```
./artisan auth:email -o -m -s
PHP Parse error:  syntax error, unexpected '?' in /vagrant/vendor/ntavelis/auth-email/src/Commands/actions/FilesInteractions.php on line 92
```

## Detailed description
When running the above artisan command the error clearly points out the issue on line 92 and the use of the coalesce operator which is implemented in PHP 7.x.  In order to make the code more widely useable on other versions of PHP this call can be refactored.

**edit:**
I also found one other location that is PHP 7 specific.  Line 25 of ActivateAccount.php
```
PHP message: PHP Fatal error:  Uncaught exception 'ErrorException' with message 'Argument 1 passed to App\Mail\ActivateAccount::__construct() must be an instance of App\Mail\String, string given, called in /vagrant/vendor/ntavelis/auth-email/src/Services/EmailAdapter.php on line 30 and defined' in /vagrant/app/Mail/ActivateAccount.php:25
```

## Context
Due to limitations of my project I am limited to pre PHP 7.  
 
The benefit to others, is that it can be used on a wider code base than just PHP 7.x

## Possible implementation
Refactor line 92 in FilesInteractions.php:
`$newFile = $newFile ?? $oldFile;`

with something similar to:

```
if(! isset($newFile) || $newFile == NULL ){
	    	$newFile = $oldFile;
	    }
```
**edit**
**ActivateAccount.php change**
Line 25:
`public function __construct(String $link)`
The use of type-hinting not supported till 7.x

Change to:
`public function __construct($link)`

## Your environment
Environment:
* PHP 5.6.30
* Ubuntu 14.04

**Comment by ntavelis** [comment]
Your commit fixes this issue. 

Thank you.
