### ISSUE TITLE
Namespace Error in Capitalisation / Linux Servers

### ISSUE THREAD

**Issue by DungeonGirl** [ntavelis/auth-email#14]
## Detailed description

When following installation instructions on a Linux install you are presented with the error

php artisan auth:email
[ReflectionException]
  Class Ntavelis\AuthEmail\Commands\Actions\Actions does not exist

This is because the author has used a Windows machine in development and not spotted case-sensitivity issues.

## Context

This is important because people use Linux servers.  They do it because Linux is more secure, it's last major security flaw required you pressing enter 22 times to get root access, but on Windows you only needed to press enter once :P  - yay for patches :)

## Possible implementation

This can be solved by renaming the folder "actions" to "Actions", and changing the namespace declaration within all the files underneath this folder to a capital A.

Then run "composer update" to rebuild the compiled thingamibobs.

## Your environment

php artisan --version
Laravel Framework 5.4.25

php -v
PHP 7.1.5-1+deb.sury.org~trusty+2 (cli) (built: May 22 2017 13:39:01) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.5-1+deb.sury.org~trusty+2, Copyright (c) 1999-2017, by Zend Technologies

uname -r
3.4.0+

cat /etc/issue
Ubuntu 14.04.5 LTS \n \l

**Comment by DungeonGirl** [comment]
Additionally, "routes/web.php" I just found was named "routes/Web.php" after running the installation.

**Comment by ntavelis** [comment]
Hello, and thank you for your report. I will test it on a linux environment and I will come back to you.

**Comment by DungeonGirl** [comment]
I also found the route did not appear to set up properly for user activation, I hacked this in which is a bit of a guess
Route::get( '/user.activate' , [ 'use' => 'App\Http\Controllers\Auth\RegisterController@register' , 'as' => 'user.activate' ] );

I'm just setting up a mail server right now so I'm not sure if there is anything else yet.

**Comment by ntavelis** [comment]
I managed to reproduce your issue. I am working on a fix right now.

**Comment by ntavelis** [comment]
Thank you for pointing it out on me

**Comment by ntavelis** [comment]
I am going to close this issue, the problems are solved, I have personally tested it into linux OS. You can use the new 1.3 version to solve your problems.
