### ISSUE TITLE
when did the EmailService instantiate

### ISSUE THREAD

**Issue by xralphack** [ntavelis/auth-email#15]
Thanks for making this elegant package, 
just want to ask a question about how the dependency inject woks.

public function __construct(EmailService $EmailService)

you pass the variable into construct, but I can't find the instantiation of the EmailService class

**Comment by xralphack** [comment]
I found the ans on laravel document, it depends on Laravel service container

**Comment by ntavelis** [comment]
Hello and thank you,

yeah it resolves the instance out of the Laravel's container, because it is typehinted.

Cheers :D
